import Link from "next/link";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ChatWidget from "@/components/ChatWidget";
import { projects } from "@/lib/projects";

export const dynamic = "force-dynamic";

const stack = ["Next.js", "TypeScript", "React", "Node.js", "Three.js", "Tailwind", "Postgres", "Figma"];
const services = ["Frontend engineering", "Full-stack development", "Interface design", "Performance & accessibility"];
const principles = [["01", "Clarity", "Make the important thing obvious."], ["02", "Craft", "Sweat the details users actually notice."], ["03", "Systems", "Build foundations that stay maintainable."]];
const process = [["01", "Understand", "Goals, users, constraints."], ["02", "Shape", "Structure, interface, interaction."], ["03", "Build", "Components, APIs, data, testing."], ["04", "Refine", "Performance, accessibility, polish."]];

export default function Home() {
  const featured = projects.slice(0, 4);
  return <div className="neo-shell min-h-screen flex flex-col">
    <Header />
    <main id="main-content" className="flex-1">
      <section className="neo-hero"><div className="hero-grid-bg" aria-hidden="true" /><div className="hero-orb hero-orb-a" aria-hidden="true" /><div className="hero-orb hero-orb-b" aria-hidden="true" /><div className="neo-container hero-layout"><div className="hero-kicker"><span>01</span> BIBASH POUDEL <i /></div><div className="hero-title-wrap"><h1><span>Build.</span><span className="outline">Think.</span><span>Ship.</span></h1><div className="hero-side-note">FULL-STACK<br />DEVELOPER<br /><span>NEPAL / 2026</span></div></div><div className="hero-bottom"><p className="hero-intro">I build web experiences where <strong>good engineering</strong> meets thoughtful interface design.</p><div className="hero-actions"><Link href="/projects" className="magnetic-link">See the work <span>↗</span></Link><Link href="/about" className="quiet-link">About me</Link></div><div className="scroll-mark"><span>SCROLL</span><b>↓</b></div></div></div></section>
      <section className="manifesto"><div className="neo-container manifesto-grid"><span className="section-index">02 / INTRODUCTION</span><div><p className="manifesto-big">I turn ideas into <em>working products</em> — from the first interface to the systems behind it.</p><p className="manifesto-small">My focus is practical: understand the problem, design a clear solution, write solid code, and keep improving it after launch.</p></div></div></section>
      <section className="work-section" id="work"><div className="neo-container"><div className="section-top"><div><span className="section-index">03 / SELECTED WORK</span><h2>Things I&apos;ve<br /><em>built.</em></h2></div><Link href="/projects" className="circle-link">ALL WORK ↗</Link></div><div className="neo-projects">{featured.map((project,index)=><Link href={`/projects/${project.slug}`} key={project.slug} className={`neo-project ${index===0?"neo-project-wide":""}`} style={{"--project-accent":project.color} as React.CSSProperties}><div className="project-meta"><span>0{index+1}</span><span>{project.tech.slice(0,2).join(" / ")}</span></div><div className="project-art"><div className="art-lines" /><strong>{project.title.charAt(0)}</strong><span className="art-label">PROJECT / {String(index+1).padStart(2,"0")}</span></div><div className="project-caption"><div><h3>{project.title}</h3><p>{project.description}</p></div><span className="project-arrow">↗</span></div></Link>)}</div></div></section>
      <section className="capabilities"><div className="neo-container"><div className="section-top"><div><span className="section-index">04 / WHAT I DO</span><h2>Useful<br /><em>by design.</em></h2></div><p className="cap-intro">I work across the product surface, from interface decisions to the code that makes them real.</p></div><div className="cap-list">{services.map((item,i)=><div key={item}><span>0{i+1}</span><strong>{item}</strong><b>↗</b></div>)}</div></div></section>
      <section className="principles-section"><div className="neo-container"><span className="section-index">05 / HOW I WORK</span><div className="principles-heading"><h2>Less noise.<br /><em>More intent.</em></h2><p>Three simple rules guide the work.</p></div><div className="principles-grid">{principles.map(([num,title,text])=><article key={num}><span>{num}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="process-section"><div className="neo-container process-layout"><div><span className="section-index">06 / PROCESS</span><h2>From rough<br />idea to <em>real.</em></h2></div><div className="process-rail">{process.map(([num,title,text])=><div className="process-step" key={num}><span>{num}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></section>
      <section className="toolkit-section"><div className="neo-container"><div className="section-top"><div><span className="section-index">07 / TOOLKIT</span><h2>The stack<br /><em>behind it.</em></h2></div><p className="cap-intro">Technologies I use to turn designs and requirements into maintainable software.</p></div><div className="toolkit-grid">{stack.map((item,i)=><div key={item}><span>0{i+1}</span><strong>{item}</strong></div>)}</div></div></section>
      <section className="experience-section"><div className="neo-container"><span className="section-index">08 / EXPERIENCE</span><div className="experience-row"><div className="experience-year">2026</div><div><h2>Web development<br /><em>& product work.</em></h2><p>Building production websites and digital experiences across WordPress, React, Next.js, Figma, hosting and performance optimization.</p></div><span className="experience-mark">01</span></div><div className="experience-row secondary"><div className="experience-year">NOW</div><div><h2>Learning through<br /><em>experiments.</em></h2><p>Exploring 3D, creative development, modern frontend architecture and better ways to make technical work useful.</p></div><span className="experience-mark">02</span></div></div></section>
      <section className="lab-section"><div className="neo-container lab-layout"><div><span className="section-index">09 / LAB</span><h2>Curious<br /><em>by default.</em></h2></div><div className="lab-note"><div className="lab-orbit" /><span>EXPERIMENTS</span><p>Side experiments are where I explore interaction patterns, graphics, 3D and game-development ideas without losing the engineering fundamentals.</p><Link href="/lab" className="underline-link">Enter the lab →</Link></div></div></section>
      <section className="writing-section"><div className="neo-container"><div className="section-top"><div><span className="section-index">10 / NOTES</span><h2>Things I&apos;m<br /><em>figuring out.</em></h2></div><Link href="/blog" className="circle-link">WRITING ↗</Link></div><div className="writing-grid"><article><span>01 / ENGINEERING</span><h3>Building interfaces that stay maintainable.</h3><p>Notes on components, structure and the small decisions that add up.</p></article><article><span>02 / PROCESS</span><h3>Making technical work easier to understand.</h3><p>Thoughts on translating requirements into useful, clear experiences.</p></article><article><span>03 / LEARNING</span><h3>Experiments, mistakes and better approaches.</h3><p>A running record of things worth trying.</p></article></div></div></section>
      <section className="about-section"><div className="neo-container about-layout"><span className="section-index">11 / ABOUT</span><div className="about-main"><div className="about-number">BP<span>01</span></div><div><h2>Developer.<br /><span>Designer.</span><br />Problem solver.</h2><p>Based in Nepal, building for the web. I care about useful products, clean implementation and interfaces that don't get in the user's way.</p><Link href="/about" className="underline-link">Read the full story →</Link></div></div></div></section>
      <section className="contact-section"><div className="neo-container"><span className="section-index">12 / CONTACT</span><div className="contact-heading"><h2>Have a good<br /><em>problem?</em></h2></div><div className="contact-footer"><Link href="/contact" className="big-contact">Start a conversation <span>↗</span></Link><a href="mailto:bibashpoudel@email.com">bibashpoudel@email.com</a></div></div></section>
    </main><Footer /><ChatWidget /></div>;
}
